# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    AZURE WEBAPP_NAME: apitesttool # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: ',' # set this to the path to your web app project, defaults to the repository root
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.6'  # Specify the .NET version we are using

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: ./deploy.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
