name: CI/CD 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.204'  # Specify the .NET 

    - name: Restore dependencies
      run: dotnet restore src/MyProject/APITestingTool.csproj

    - name: Build
      run: dotnet build src/MyProject/APITestingTool.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test src/MyProject/APITestingTool.csproj --no-build --verbosity normal
