name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore ./APITestingToolProject.sln
    - name: Build
      run: dotnet build ./APITestingToolProject.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ./APITestingToolProject.sln --configuration Release --no-restore --no-build
 
